version: '3.8'

services:
  # Nginx as a reverse proxy for Vue.js and FastAPI
  nginx:
    container_name: eza_frontend_prod
    build:
      context: ./nginx
    environment:
      VITE_API_SERVER: https://www.ezanalytics.dbaprojects.com
    # image: nginx:latest
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      - fastapi
      - mongo
      - postgres
      - redis
    networks:
      - analytics_network

  # FastAPI
  fastapi:
    container_name: eza_api_prod
    build:
      context: ./api
    working_dir: /app
    environment:
      ORIGINS: https://www.ezanalytics.dbaprojects.com
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASSWORD: ezaMongoPass
      PG_HOST: postgres_eza_container
      PG_USER: postgres
      PG_PASSWORD: mypassword
      REDIS_HOST: redis
    ports:
      - 5050:5050
    volumes:
      - ./api:/app
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 5050
    depends_on:
      - postgres
      - redis
      - mongo
    networks:
      - analytics_network

  # PostgreSQL
  postgres:
    container_name: eza_postgres_prod
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    expose:
      - "5432"
    volumes:
      - postgres-data:/data
    networks:
      - analytics_network

  # Redis
  redis:
    container_name: eza_redis_prod
    image: redis:latest
    command: redis-server && redis-cli FLUSHALL
    expose:
      - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - analytics_network

  # MongoDB
  mongo:
    container_name: eza_mongo_prod
    # image: mongo:latest
    build:
      context: ./mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
    volumes:
      - mongo-data:/data
    networks:
      - analytics_network

networks:
  analytics_network:

volumes:
  ezanalytics-vue:
  fastapi:
  mongo-data:
  postgres-data:
  redis-data:
  redis-conf:
