version: '3.8'

services:
  # Vue.js application
  vue:
    image: node:14
    working_dir: /app
    volumes:
      - ./vue-app:/app
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"
    networks:
      - analytics_network

  # Nginx as a reverse proxy for Vue.js and FastAPI
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - vue
      - fastapi
    networks:
      - analytics_network

  # FastAPI
  fastapi:
    build:
      context: ./fastapi
    ports:
      - 5050:5050
    volumes:
      - ./fastapi-app:/app
    depends_on:
      - postgres
      - redis
      - mongo
    networks:
      - analytics_network
    # image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    # ports:
    #   - "8000:80"

  # PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - analytics_network

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - analytics_network

  # MongoDB
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - analytics_network

networks:
  analytics_network:
