version: '3.8'

services:
  # Vue.js application
  vue:
    container_name: eza_vue
    image: node:21
    working_dir: /app
    environment:
      VITE_API_SERVER: http://lvh.me:5050
    volumes:
      - ./nginx/vue:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "8080:8080"
    networks:
      - analytics_network

  # FastAPI
  fastapi:
    container_name: eza_api
    build:
      context: ./api
    working_dir: /app
    environment:
      ORIGINS: http://lvh.me,http://lvh.me:8080
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASSWORD: ezaMongoPass
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: mypassword
      REDIS_HOST: redis
    ports:
      - 5050:5050
    volumes:
      - ./api:/app
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 5050 --reload
    depends_on:
      - postgres
      - redis
      - mongo
    networks:
      - analytics_network

  # PostgreSQL
  postgres:
    container_name: eza_postgres
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    expose:
      - "5432"
    volumes:
      - postgres-data:/data
    networks:
      - analytics_network

  # Redis
  redis:
    container_name: eza_redis
    image: redis:latest
    command: redis-server && redis-cli FLUSHALL
    expose:
      - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - analytics_network

  # MongoDB
  mongo:
    container_name: eza_mongo
    build:
      context: ./mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ezaMongoPass
    expose:
      - "27017"
    volumes:
      - mongo-data:/data
    networks:
      - analytics_network

networks:
  analytics_network:

volumes:
  fastapi:
  mongo-data:
  postgres-data:
  redis-data:
  redis-conf:
