version: '3.8'

services:
  fastserver:
    # image: dockerspike
    build:
      context: ./fastapi
      # dockerfile: ./Dockerfile
    ports:
      - 5050:5050
  nginx:
    # restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
