version: '3.8'

services:
  fastserver:
    build:
      context: ./fastapi
    ports:
      - 5050:5050

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis_db_container
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf:

